version: '3.8'

services:
  user-micro:
    build: ./user
    ports:
      - "8081:8080"

  product-micro:
    build: ./product
    ports:
      - "8082:8080"
    depends_on:
      - user-micro

  order-micro:
    build: ./order
    ports:
      - "8083:8080"
    depends_on:
      - user-micro
      - product-micro

  batch-micro:
    build: ./batch
    ports:
      - "8084:8080"
    depends_on:
      - user-micro
      - product-micro
      - order-micro
