version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  user-micro:
    build: ./user
    ports:
      - "8080:8080"
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect'
      - 'spring.jpa.hibernate.ddl-auto=update'
      - 'spring.jpa.show-sql=true'
      - 'spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true'
      - 'spring.batch.jdbc.initialize-schema=always'

  product-micro:
    build: ./product
    ports:
      - "8081:8080"
    depends_on:
      - user-micro
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect'
      - 'spring.jpa.hibernate.ddl-auto=update'
      - 'spring.jpa.show-sql=true'
      - 'spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true'
      - 'spring.batch.jdbc.initialize-schema=always'

  order-micro:
    build: ./order
    ports:
      - "8082:8080"
    depends_on:
      - user-micro
      - product-micro
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect'
      - 'spring.jpa.hibernate.ddl-auto=update'
      - 'spring.jpa.show-sql=true'
      - 'spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true'
      - 'spring.batch.jdbc.initialize-schema=always'

  batch-micro:
    build: ./batch
    ports:
      - "8083:8080"
    depends_on:
      - user-micro
      - product-micro
      - order-micro
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect'
      - 'spring.jpa.hibernate.ddl-auto=update'
      - 'spring.jpa.show-sql=true'
      - 'spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true'
      - 'spring.batch.jdbc.initialize-schema=always'
